### ISSUE TITLE
Convert AES.randomIV to String

### ISSUE THREAD

**Issue by netgfx** [krzyzanowskim/CryptoSwift#166]
I'm trying:

let ivpre = AES.randomIV(16)
let ivnsdata = NSData(bytes: ivpre)
let nsparams = NSString(data: ivnsdata, encoding: NSUTF8StringEncoding)
let iv:String = (nsparams as! String)

but no luck the nsparams is nil

**Comment by krzyzanowskim** [comment]
why would you expect proper string frommrandom bytes?

**Comment by netgfx** [comment]
So a more "correct" way would be to have ivpre.toHexString() ?

**Comment by netgfx** [comment]
Basically my problem is that when setting this
let _encrypted:[UInt8] = try! AES(key: _key, iv:ivpre, blockMode: .CBC).encrypt(nsdata!.arrayOfBytes(), padding: PKCS7())
with ivpre to be UInt8 I'm getting the following error: "Type of expression is ambiguous without more context" but when setting the iv as string I don't get this error.
Any idea what might be wrong?

**Comment by krzyzanowskim** [comment]
toHexString() returns hex representation of string, it's not the same: hex "ab" (171) is not the same what string "ab". That said, if you want randomly generated string and you have to do it by your own, or use array of bytes.

The ambiguity is because (I assume) `_key` is String and `ivpre` is [UInt8] and there is no constructor for such arguments. 

![screen shot 2015-11-22 at 11 45 21](https://cloud.githubusercontent.com/assets/758033/11323263/926bf26a-910e-11e5-8bdb-a636d8687f2a.png)

**Comment by netgfx** [comment]
So if I want to use the result of AES.randomIV(16) I have to also convert the key from string to UInt8 correct?

**Comment by krzyzanowskim** [comment]
yes
