### ISSUE TITLE
Using PKCS7 will crash

### ISSUE THREAD

**Issue by uwunmn** [krzyzanowskim/CryptoSwift#184]
when i encoded 'plaintext' with 'aes', and decoded with 'aes2'
PKCS7 crashed in 'Array(bytes[0..<(bytes.count - padding)])'.
test case like this,
```swift
    func testAESWithWrongKey() {
        let key:[UInt8] = [0x2b,0x7e,0x15,0x16,0x28,0xae,0xd2,0xa6,0xab,0xf7,0x15,0x88,0x09,0xcf,0x4f,0x3c];
        let key2:[UInt8] = [0x22,0x7e,0x15,0x16,0x28,0xae,0xd2,0xa6,0xab,0xf7,0x15,0x88,0x09,0xcf,0x4f,0x33];
        let iv:[UInt8] = [0x00,0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,0x09,0x0A,0x0B,0x0C,0x0D,0x0E,0x0F]
        let plaintext:[UInt8] = [49, 46, 50, 50, 50, 51, 51, 51, 51]
        
        let aes = try! AES(key: key, iv:iv, blockMode: .CBC)
        let aes2 = try! AES(key: key2, iv:iv, blockMode: .CBC)
        XCTAssertTrue(aes.blockMode == .CBC, "Invalid block mode")
        let encrypted = try! aes.encrypt(plaintext, padding: PKCS7())
        let decrypted = try! aes2.decrypt(encrypted, padding: PKCS7())
        XCTAssertEqual(decrypted, plaintext, "decryption failed")
    }
```

**Comment by krzyzanowskim** [comment]
Thank you for the report. I addressed this scenario by throwing error from the padding function, this way decryption will fail completely when invalid padding value is detected.

**Comment by danzaph** [comment]
There are a couple of problems:

1. "InvalidPaddingValue" is a misnomer, it does not provide accurate padding information, only if the last byte is greater than the block size. There are many (most?) incorrect paddings that are not reported. a simple example would be a padding with the last two bytes 0x01, 0x02 which is incorrect padding

2. Reporting padding errors is a poor idea in that it leaks information. Note that Common Crypto does not report padding errors by design. Reporting all padding errors allows a user to easily make a mistake by reporting these back to the client creating a padding oracle, such an implementation along with CBC mode can allow an attacker to obtain the plain text without knowing the encryption key.

3. Some developer incorrectly rely on bad padding errors to determine if the decryption was correct. There have been several complaints on the Apple developer forums that developers were relying on padding errors (or lack of) to determine correct decryption.

The solution is not to report any padding error information and also not to crash attempting to remove bad padding. If a developer wants to determine correct decryption thy should use a MAC or authentication encryption algorithm.

**Comment by krzyzanowskim** [comment]
sounds good, willing to work on patch for that?

**Comment by danzaph** [comment]
Marcin,

Just delete the throw, instead:
    if finalLength < 0 {
        return bytes;
    }
and delete:
    throws -> [UInt8]

Essentially if there is a padding the chances are either it is a Padding Oracle attack, the wrong key the wrong data format or another padding (mcrypt null). In any of these instances should an error be returned.

Sure, the padding is available to a developer, he just needs to decrypt padded data with a no-padding option. So this is just to keep the less well informed from creating a PaddingOracle by error. That is why Apple removed the padding error several years ago from CCCrypt.

The only errors that should be reported are programming errors such as incorrect options, Any report about the encryption leaks information. The encryption should be a black box, data in, data out, no other information or context.

If the developer wants authentication then he should use a MAC.

See:
	The Padding Oracle Attack: http://robertheaton.com/2013/07/29/padding-oracle-attack/ 
	Padding oracle attacks: in depth: https://blog.skullsecurity.org/2013/padding-oracle-attacks-in-depth 
	Practical Padding Oracle Attacks: http://netifera.com/research/poet/PaddingOracleBHEU10.pdf 

Why report this now? Well, it so happens my wife is a crypto domain expert WRT certain areas, she has a CISSP (and I studied with her for that test, I do not have 5 years of 100% supervised experience so I could not even take the test). So it is not uncommon to discuss crypto at home or in this case over dinner in Mexico City a couple of nights ago and the topic came up of Padding Oracle attacks along with DES parity forcing/checking. There is a lot of legacy code that has minot errors and Padding Oracle attacks are common.

Dan
