### ISSUE TITLE
Is there any way to decode a MD5/SHA256  to String

### ISSUE THREAD

**Issue by dromerobarria** [krzyzanowskim/CryptoSwift#243]
Hi , very nice job with CryptoSwift ,

I would like to know , it is posible to decode or convert a MD5/SHA256 to String, cause I got an image in md5 so i would like to decode it.

Thanks in advance.

**Comment by paulblakely** [comment]
dromerobarria, hasing algorithms are intended to be a one way street. Once something has been hashed, the entire idea is that it's difficult to "unhash." The only way to do so is by hashing random values until you reach the same hash.

Try encoding your images with base64 instead of hashing them with a hashing method.
