### ISSUE TITLE
Decrypting string with whitespace

### ISSUE THREAD

**Issue by mathiasverhoeven120** [krzyzanowskim/CryptoSwift#245]
Hello,
I have a question concerning the class Swift+AES. 
Some values that I encrypt using this class have whitespaces in them. 
(e.g. : A3MfidyyDQ0zX7Q KHFrJTw54cx6yKLmZ8kZXf16SEw=)
When I want to decrypt these values I the following error : " fatal error: unexpectedly found nil while unwrapping an Optional value "
How can I prevent values being encrypted without whitespaces?
![screenshot 2016-04-19 09 13 15](https://cloud.githubusercontent.com/assets/11355549/14630616/03722ac2-060f-11e6-9d01-afb4286ff186.png)

Thanks in advance

Mathias Verhoeven

**Comment by krzyzanowskim** [comment]
@mathiasverhoeven120 if NSData can't decode Base64 input, it's due to invalid input data. This may be due to transcoding data while transfer (eg. over the http), yet I never noticed problems with NSData and Base64 itself. 

You can see if output of line 10 i exactly the same as input for line 16 - it is probably not.

Closing this issue as not really CryptoSwift issue, feel free to comment if you think it is CryptoSwift issue anyway.
