### ISSUE TITLE
Cannot catch error when setting wrong key

### ISSUE THREAD

**Issue by cesarvarela** [krzyzanowskim/CryptoSwift#315]
HI, I'm not able to catch the error being thrown (or is it that no error is thrown? ) when trying to decrypt something with the wrong key: 
```
do {
  let encrypted = Data(base64Encoded:  encryptedText)!
  let decrypted = try encrypted.decrypt(cipher: AES(key: key))
  let originalMessage = String(data: decrypted, encoding: String.Encoding.utf8)
}  catch  {
  controller.decodedMessage = "Incorrect password!"
}
```
For the moment I know that the key is wrong because decoding the decrypted data results in `nil` 
And I know the rest of the code works because when setting the correct key I get the original message back.

**Comment by krzyzanowskim** [comment]
I'm not sure If I understand fully. Can you please paste full code with data, so I can paste it to Playground and see output ?

**Comment by cesarvarela** [comment]
```
do {
    let key = "somepassword".utf8.map({$0}).md5()
    let message = "this is the message".data(using: String.Encoding.utf8, allowLossyConversion: false)!
    
    //encrypt data with key = "somepassword"
    let encrypted = try message.encrypt(cipher: AES(key: key))
    
    
    // decrypt with original password
    var originalData = try encrypted.decrypt(cipher: AES(key: key))
    var originalMessage = String(data: originalData, encoding: String.Encoding.utf8)
    
    // decryot with wrong password
    let wrongPassword = "whatever".utf8.map({$0}).md5()
    
    // I'm expecting this to throw but seems like I'm misusing the framework..
    originalData = try encrypted.decrypt(cipher: AES(key: wrongPassword))
    originalMessage = String(data: originalData, encoding: String.Encoding.utf8)
    
} catch {
    print(error)
}
```

What I want to know is a how to detect when the user inserts a wrong password (consider I'm a crypto-n00b :D )

**Comment by krzyzanowskim** [comment]
`originalMessage: String` is nil and this is as expected.

You get bytes as result of decryption. It may be invalid/unexpected but this is due to given key. The key itself can't be validated. The key is used to decryption and you get the result.

Then you build string out of it, and happen that resulting sequence of bytes (see marked below) is not a valid String, this is why it return with nil.

![screen shot 2016-08-31 at 00 43 01](https://cloud.githubusercontent.com/assets/758033/18109797/f44f8530-6f13-11e6-81da-4e74dfeb0aa5.png)
