### ISSUE TITLE
NSAllocateMemoryPages() failed when calculate multiple md5

### ISSUE THREAD

**Issue by oyljerry** [krzyzanowskim/CryptoSwift#366]
Hi.
I use CryptoSwift to calculate 2000 image files, My code is very simple as below. Please check it. Thanks~

```
let md5 = data.md5();
```

I found there are two issues about CryptoSwift.

```
1. It will crash after calculate 60 image files.
```

**\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* NSAllocateMemoryPages(4513894) failed'
**\* First throw call stack:
(0x1830eedb0 0x182753f80 0x1830eecf8 0x183a479f4 0x183a1d10c 0x1839e7988 0x100a88fa8 0x100a2b1f8 0x10013d354 0x18ce327a0 0x18ce1f67c 0x18ce28cc4 0x18ce2d564 0x18ce32420 0x10013aa04 0x10013ac04 0x10013d510 0x1830e0f58 0x18ce7fa50 0x10013a308 0x100139c58 0x100139ca0 0x100d31a7c 0x100d31a3c 0x100d40c9c 0x100d40364 0x182d51470 0x182d51020)
libc++abi.dylib: terminating with uncaught exception of type NSException

```
2. md5 calculation is very slow than CC_MD5() API.
```

**Comment by krzyzanowskim** [comment]
you run out of memory. But you shoudnt. Memory usage by calculations is O(1) and is rather low. When called from Data extension it will allocate as much memory as data itself of course.

 is there a chance you can attach example project? 

when it comes to speed, you cant compete with asm or even C with Swift. The compiler just cant generate as fast code. It should be as fast as possible though. There were recently applied performance changes to all digests, md5 should benefit out of it as well, I can take another look for md5 itself is there is a room for improvement, though it will never be faster than possible.
Another thing is that you should have build CryproSwift in release mode with "while module optimization" enabled, otherwise performance (especially in debug mode) is beyond any scale.

**Comment by krzyzanowskim** [comment]
@oyljerry can't confirm the issue with the memory.
My tests with array of 1_048_576 bytes (1 MB) takes about 0.02s to calculate and I don't think it can be done any faster as of today.
