### ISSUE TITLE
Release Build - Architecture Problem

### ISSUE THREAD

**Issue by oyenigun** [krzyzanowskim/CryptoSwift#399]
Hi,
I am working with debug mode well. But I want to get release app. When I try the compile release, I am getting error like below;

Use of unresolved identifier 'AES'
Use of unresolved identifier 'PKCS7'
vs..

if I set enable to "Build Active Architecture Only" true and select iPhone 6s emulator, it works well. But I can' t create archive this way.

I tried to clean and delete derived data. It didn't work.

Xcode Version : Version 8.0 (8A218a)
Swift Version : 2.3

Thanks for help!

**Comment by krzyzanowskim** [comment]
Swift 2.3? what version of CryptoSwift you're using?

**Comment by krzyzanowskim** [comment]
Ok, I'm going to close this issue. It looks like configuration problem rather than something I can control. There are several of possible installation techniques you can try [README#installation](https://github.com/krzyzanowskim/CryptoSwift#installation).

Feel free to reopen if you think there is anything I can do about the issue. You can also attach the project to I can take a look at it.
