### ISSUE TITLE
ChaCha20 random IV

### ISSUE THREAD

**Issue by kubatruhlar** [krzyzanowskim/CryptoSwift#475]
`ChaCha20.blockSize` is 64 but `precondition` condition requires 8/12.

**Comment by krzyzanowskim** [comment]
It's just a original design that has been adjusted https://tools.ietf.org/html/rfc5116#section-3.2

**Comment by Dschee** [comment]
I don't think this issue is resolved in the latest release, it's still apparent. Maybe the OP didn't make clear what the issue is. At least this is what I'm trying and what throws an error:

```swift
let initialVector = ChaCha20.randomIV(ChaCha20.blockSize)
try ChaCha20(key: key.bytes, iv: initialVector).encrypt(plaintext.bytes)
```

So, the problem is that – whatever design has been adjusted – the adjustment hasn't been done thouroughly within CryptoSwift as the precondition and the blockSize constant don't fit each other. They should be streamlinked for the `ChaCha20.randomIV(ChaCha20.blockSize)` to always provide a valid initial vector, no?
