### ISSUE TITLE
Encrypting twice?

### ISSUE THREAD

**Issue by gloparco** [krzyzanowskim/CryptoSwift#77]
Hey Marcin, another question that I hope is not too tangental...

Scenario: you develop an app that uses CloudKit/iCloud to store documents; you want to use CryptoSwift for PGP

iCloud automatically encrypts your data on transmission using TLS 1.2, and then they encrypt your data on their server using "a minimum of 128-bit AES encryption".  It also can encrypt the data on-device when it is locked.

My question is - are there any dangers, or perhaps just tips with using CryptoSwift in such an app?  Will the "multiple encryption" cause a vulnerability (e.g., magic numbers)?  Are there considerations that can be factored in, such as " random padding"?

Thanks again!

**Comment by krzyzanowskim** [comment]
Actually you cant use CryptoSwift for PGP because PGP is based on asymmetric encryption while CryptoSwift support (today) only symmetric ciphers

Multiple encryption in general will not cause a vulnerability, as long as not vulnerable ciphers and protocols are used. Encrypt twice is as same secure as encrypt once for secure cipher.
