### ISSUE TITLE
CryptoSwift causes `contains invalid products.` warning during compilation, and codesigning crash on launch on macOS (1.3.5 and 1.3.4)

### ISSUE THREAD

**Issue by Pearapps** [krzyzanowskim/CryptoSwift#840]
**Describe the bug**

Trying to build and run with CryptoSwift included via SPM causes invalid products warning and crash on launch indicating the code signing is not correct.

**Reproduce**
Steps to reproduce:
1. Add to project via SPM to a macOS app
2. Try to build and run
3. Observe crash and `contains invalid products.` warning generated.

**Workaround**

CryptoSwift 1.3.3 works as designed and correctly with no warning or crash.

**Comment by krzyzanowskim** [comment]
can you attach sample project? can't reproduce it.

make sure your derived data is cleared due to a certain SPM bug.

**Comment by Pearapps** [comment]
Here are updated steps:

1. Create a new project
2. Add to project via SPM to a macOS app
3. Add "App Groups" and "Hardened Runtime" under "Signing & Capabilities" in Xcode (in your app target)
4. Build and run
5. Observe crash reason: `not valid for use in process using Library Validation: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)`

**Comment by krzyzanowskim** [comment]
You need this option

<img width="322" alt="Screen Shot 2020-11-22 at 14 38 16" src="https://user-images.githubusercontent.com/758033/99905350-920bd200-2cd0-11eb-98e8-53041f9d0d74.png">

I don't know the way to work around it unless building from the source, also see https://github.com/electron-userland/electron-builder/issues/3940#issuecomment-501702531

**Comment by krzyzanowskim** [comment]
I've made a note about this in README. That's something I can't workaround on my side though.

**Comment by krzyzanowskim** [comment]
The actual solution is that it won't work with "Ad Hoc" signing in your app. That's how Xcode signing works.

<img width="435" alt="Screen Shot 2020-11-22 at 16 26 06" src="https://user-images.githubusercontent.com/758033/99907839-7fe56000-2cdf-11eb-9fae-c9dbde4c2300.png">

**Comment by Pearapps** [comment]
> The actual solution is that it won't work with "Ad Hoc" signing in your app. That's how Xcode signing works.
> 
> <img alt="Screen Shot 2020-11-22 at 16 26 06" width="435" src="https://user-images.githubusercontent.com/758033/99907839-7fe56000-2cdf-11eb-9fae-c9dbde4c2300.png">

Moving to "Development" doesn't fix the issue (it actually created an additional warning, as far as I can tell about duplicate files).

Is the expectation really to make developers disable library validation...? That doesn't really seem right?

An option to not have the binary distributed, but rather distributing the source like it was done in 1.3.3 and prior would be _really_ great.

**Comment by krzyzanowskim** [comment]
> Is the expectation really to make developers disable library validation...? That doesn't really seem right?

this is right and only solution if you want to use "Ad Hoc" signing. But you shouldn't need it.

The binary frameworks doesn't work with `Ad Hoc` because that's how code signing is designed, and this is what the message you reported is about.

There's no good solution that can solve all problems. Binary distribution is a solution to address swift runtime performance when used with Xcode. What you experience is combined Xcode Signing thing and SPM not working great with Xcode.

Now, If you see a "duplicate" something, it's most likely the SPM cache/DerivedData thing, where you have to clear the field of the leftovers. But maybe you can share what's the exact message, or how to reproduce it.

I just created the empty project, added SPM dependency, enabled Hardened Distribution and it seem to work just fine: [CryptoSwiftTestApp.zip](https://github.com/krzyzanowskim/CryptoSwift/files/5580758/CryptoSwiftTestApp.zip)


<img width="1618" alt="Screen Shot 2020-11-23 at 02 02 11" src="https://user-images.githubusercontent.com/758033/99922260-f90ca380-2d2f-11eb-91bd-29a8c307e61a.png">

**Comment by Pearapps** [comment]
That example project exhibits the same issue for me :/ 

> There's no good solution that can solve all problems. Binary distribution is a solution to address swift runtime performance when used with Xcode. What you experience is combined Xcode Signing thing and SPM not working great with Xcode.

Totally understand, but would take slower runtime versus not being able to use at all.

**Comment by krzyzanowskim** [comment]
Can you show what's the error with the sample project? maybe there's something we ca do about it.

Stick to 1.3.3 if everything else wont work for you. Even if I'd change it back bow, due to Xcode issue, it's even worse overall.

I don't know, maybe I'll come up with something to address that, but I can't fix Xcode nor SPM. As of today there's no easy way to offer source and binary version of module at the same time.

**Comment by Pearapps** [comment]
/Users/kenny/Library/Developer/Xcode/DerivedData/CryptoSwiftTestApp-ehlaksrokaklkpcwxyngpkkelbzc/Build/Products/Debug/CryptoSwiftTestApp.app/Contents/MacOS/../Frameworks/CryptoSwift.framework/Versions/A/CryptoSwift: code signature in (/Users/kenny/Library/Developer/Xcode/DerivedData/CryptoSwiftTestApp-ehlaksrokaklkpcwxyngpkkelbzc/Build/Products/Debug/CryptoSwiftTestApp.app/Contents/MacOS/../Frameworks/CryptoSwift.framework/Versions/A/CryptoSwift) not valid for use in process using Library Validation: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)

The signing on the framework is incorrect, is my reading - but I don't really know.

I'll just work around this by using 1.3.3 like you mentioned and we had to do.

**Comment by krzyzanowskim** [comment]
so that's the same error message. I guess you updated the Team on the target, didn't you?

this error message is not the best message out there, but what it says is that the process signed with adhoc or custom, can't load distributed binaries.

I was able to reproduce this error with adhoc signing, but not with others.

I'm only that smart after I reach to people who work on that and told me what's that all about.

I'm sorry for the inconvenience. I love to understand why you're getting different results than I in this case. Would you be open to some online debugging session? drop me an email we can schedule something.

**Comment by krzyzanowskim** [comment]
Just in case, give it a shot 1.3.7 I just pushed. I still fight with SPM setup, maybe this time it pleases SPM gods, who knows.
