### ISSUE TITLE
How to store key and iv in the app

### ISSUE THREAD

**Issue by sergeydi** [krzyzanowskim/CryptoSwift#856]
What is the true way to store `key` and `iv` of AES algorithm on iOS app side?
It can be store in `Struct` object or use some KeyChain solution?

**Comment by NathanFallet** [comment]
The best way to store this data is in the Keychain, because it should be kept secret (so don't store it in a file or in the UserDefaults for example).

Also, you can use https://github.com/GroupeMINASTE/Keychain.swift as a wrapper for the keychain, and end with something like this: (assuming in this example that key and iv are Strings)
```swift
import Keychain
let keychain = Keychain()

// Save it
keychain.save(key, forKey: "key")
keychain.save(iv, forKey: "iv")

// Read it later
guard let key = keychain.value(forKey: "key") as? String, let iv = keychain.value(forKey: "iv") as? String else { return }
```
