### ISSUE TITLE
Add to Swift langauge

### ISSUE THREAD

**Issue by trivedi** [krzyzanowskim/CryptoSwift#90]
Now that Swift is open source, have you thought about adding CryptoSwift? CommonCrypto is a pain and this distribution makes it so much easier!

**Comment by krzyzanowskim** [comment]
Swift is not yet open source AFAIK. wonder how it will be in regard of modules, Apple did not announced release of foundation or any component but swift language.

**Comment by Jamonek** [comment]
Update?

**Comment by krzyzanowskim** [comment]
ask here: https://bugs.swift.org

**Comment by danzaph** [comment]
There are a few reasons that CryptoSwift should be be added to the Swift language or more accurately the Apple APIs

1. Cryptography is not a language feature.

2. The Apple supplied Common Crypto is in general 500 to 1000 times faster on iOS. See the "Speed Questions" issue.

3. Common Crypto is FIPS 140-2 certified. <http://csrc.nist.gov/groups/STM/cmvp/documents/140-1/140sp/140sp1514.pdf>

4. CryptoSwift is still in int's infancy, the code base lacks serious code review, as an example there was a padding error that caused crashes which was just fixed 11 days ago. That fix created an information leak.

What we should hope for is better integration between Common Crypto and Swift.

**Comment by krzyzanowskim** [comment]
how about serious code review @danzaph ? I'm ready to read one and cant't wait to work on that. I just cant do it by myself.

**Comment by krzyzanowskim** [comment]
Speaking of... I dont think CommonCrypto will join Swift in Foundation at all. OpenSSL is more common between the platforms, though OpenSSL is no FIPS certified and has its own problems especially on iOS. Personaly Im not huge fan of FIPS due to authorities involved.

**Comment by danzaph** [comment]
Hi Marcin,

> On Jan 23, 2016, at 1:31 PM, Marcin Krzyzanowski <notifications@github.com> wrote:
> Speaking of... I dont think CommonCrypto will join Swift in Foundation at all. OpenSSL is more common between the platforms, though OpenSSL is no FIPS certified and has its own problems especially on iOS. Personaly Im not huge fan of FIPS due to authorities involved.
> 

Certainly Apple is not keeping Common Crypto up-to-date and does not support OpenSSL. I would support Apple bringing back OpenSSL just for those cases Common Crypto, etc that Apple does not support.

There is some history:

Several years ago, around OSX 10.7 Apple decided not to continue providing OpenSSL because they were frequently getting developer complains of broken code because OpenSSL has poor backward compatibility in the APIs. Apple would provide the current OpenSSL and previously working code would break. I don’t know if this is the current situation or not.

Next is FIPS 140-2 certification which for many developers is mandatory. As you now it is expensive and more to the point a PITA for every small change. The current situation is, AFAIK, that OpenSSL cannot be compiled as FIPS certified because small changes are necessary for compilation. There is also the issue that OpenSSL support the hardware crypto engine in all it’s different versions.

For OSX Apple provides Security Transforms
    <https://developer.apple.com/library/mac/documentation/Security/Conceptual/SecTransformPG/EncryptionandDecryption/EncryptionandDecryption.html#//apple_ref/doc/uid/TP40010801-CH3-SW1> 
but has not provided this for iOS, one can only wonder why.

So I do not see Common Crypto support for Swift, going to Security Transforms is probably more interesting to Apple.

Unfortunately  I have not been able to go to WWDC the last two years and have been out of touch with the Security team.

Finally, you many already be aware there is a security email list that the security team responds to, there is very little traffic and I believe you have to request access: apple-cdsa@lists.apple.com.

Dan
